### ISSUE TITLE
Options to customize selected page layout

### ISSUE THREAD

**Issue by qasim90** [Origogi/Vertical_Card_Pager#2]
Is there a way to customize the layout of selected card? Specifically I want the selected card to show in a a credit card like rectangular shape but this widget only shows it as square box which looks bad. I've tried adding vertical padding to container to make it rectangular but then collapsed cards won't show. Any idea how can I achieve this?

**Comment by Origogi** [comment]
The card layout size/ratio has been developed so that the developer cannot change it.
