### ISSUE TITLE
pause video when scrolling to other element

### ISSUE THREAD

**Issue by SeymaCatikkasli** [Origogi/Vertical_Card_Pager#6]
Hi, when I add a video, I want only the front video to play and the rear ones to stop. Can you help?

**Comment by Origogi** [comment]
@SeymaCatikkasli 

Use below options
~~~
                onPageChanged: (page) { // optional
                  },
                  onSelectedItem: (index) { // optional
                  },
~~~

when selected item start resume video and un selected item stop video

**Comment by SeymaCatikkasli** [comment]
thx for help :)
