### ISSUE TITLE
Scroll items without zoom

### ISSUE THREAD

**Issue by rhamnett** [Origogi/Vertical_Card_Pager#7]
Hi thanks for the library. Is there a way to disable the zoom so that items just scroll as full sized images, without the zoom tween?

If not, can you kindly point me in the direction of the piece of source to look at.

Thanks
Richard

**Comment by Origogi** [comment]
Check this point

https://github.com/Origogi/Vertical_Card_Pager/blob/ab608920e59a0dc349bd664c6191abcb7b47f056/lib/vertical_card_pager.dart#L245
